version: '3.9'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: candidate-portal-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: candidate_portal
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - candidate-portal-network

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: candidate-portal-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      # Use Docker network hostname 'mongodb' to connect from backend container
      MONGO_URI: mongodb://admin:password123@mongodb:27017/candidate_portal?authSource=admin 
      JWT_SECRET: your_jwt_secret_here
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - candidate-portal-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: candidate-portal-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://backend:5000/api
      CHOKIDAR_USEPOLLING: "true"   # for file watching support in Docker
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - candidate-portal-network

networks:
  candidate-portal-network:
    driver: bridge

volumes:
  mongodb_data:

